-- Just an example to help
-- sounds generated by http://www.bfxr.net/

love.soundman.add("select", "playSound", "assets/select.mp3", "sfx", 1, "static")
love.soundman.add("laser", "playSound", "assets/Laser_Shoot7.wav", "sfx", 1, "static")
love.soundman.add("player_explodes", "playSound", "assets/player_explodes.wav", "sfx", 1, "static")
love.soundman.add("ship_explodes", "playSound", "assets/ship_explode.wav", "sfx", 1, "static")
love.soundman.add("ship_complete", "playSound", "assets/ship_complete.wav", "sfx", 1, "static")
love.soundman.add("player_laser", "playSound", "assets/player_laser.wav", "sfx", 1, "static")
love.soundman.add("bullet_rock", "playSound", "assets/bullet_rock.wav", "sfx", 1, "static")
